#Name: Hogan McCune
#Class: 5th Hour
#Assignment: Playground
#actually here for an assignment this time


import sys
import random
d1 = random.randint(1,100)
d2 = random.randint(1,100)
d3 = random.randint(1,100)
d4 = random.randint(1,100)
d5 = random.randint(1,100)
d6 = random.randint(1,100)
d7 = random.randint(1,100)
d8 = random.randint(1,100)
d9 = random.randint(1,100)
list = [d1,d2,d3,d4,d5,d6,d7,d8,d9]
print ("###########################")
print (" ######################### ")
print ("   #####################   ")
print ("    ###################    ")
print ("     #################     ")
print ("      ###############      ")
print ("       #############       ")
print ("        ###########        ")
print ("         #########         ")
print ("          #######          ")
print ("           #####           ")
print ("            ###            ")
print ("             #             ")
print ("HELLO! WELCOME TO ROULETTE!")
y = input("Please insert anything to begin roulette!")
list.append(y)
random.shuffle(list)
print (list)
print ("If your number is at the front or end, you are OUT!")
list.pop(0)
list.pop(8)
print (list)
input ("Begin round 2?")
print ("ROUND TWO OF THE SHUFFLER!")
random.shuffle(list)
print (list)
print ("If your number is at the front or end, you are OUT!")
list.pop(0)
list.pop(6)
print (list)
input ("Begin round 3?")
print ("WOW! HOPEFULLY YOU SURVIVE THIS NEXT ONE!")
random.shuffle(list)
print (list)
print ("If your number is at the front or end, you are OUT!")
list.pop(0)
list.pop(4)
print (list)
input ("Begin round 4?")
print ("THE SEMIFINAL ROUND! SO CLOSE!")
random.shuffle(list)
print (list)
print ("If your number is at the front or end, you are OUT!")
list.pop(3)
list.pop(0)
print (list)
input ("Begin round 5?")
print ("Now, THE FINALE!!! ONLY THE FIRST NUMBER WILL BE ELIMINATED!")
random.shuffle(list)
print (list)
print ("If your number is at the front, you got second place!")
list.pop(0)
input ("How do you feel about how the game went? After you confirm, i will show who won!")
print (list, "GOT FIRST PLACE!")